python_stack/django/django_fullstack/favorite_books_proj/books_app/urls.py
from django.urls import path
from . import views
app_name = 'books'
urlpatterns = [
    path('books', views.index, name='root'),
    path('books/create', views.create, name='create'),
    path('books/<int:book_id>/like', views.like, name='like'),
    path('books/<int:book_id>/remove_like', views.remove_like, name='remove_like'),
    path('books/<int:book_id>', views.view, name='view'),
    path('books/<int:book_id>/update', views.update, name='update'),
    path('books/<int:book_id>/delete', views.delete, name='delete'),
    path('books/my_favorites', views.user_fav, name='user_fav'),
]

python_stack/django/django_fullstack/favorite_books_proj/favorite_books_proj/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('login_app.urls'), name='login'),
    path('', include('books_app.urls'), name='books'),
]

python_stack/django/django_fullstack/favorite_books_proj/login_app/urls.py
from django.urls import path
from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='root'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('success', views.success, name='success'),
    path('logout', views.logout, name='logout')
]

python_stack/django/django_fullstack/favorite_books_proj/books_app/models.py
from django.db import models
from login_app.models import User

class BookManager(models.Manager):
    def validator(self, postData):
        errors = {}
        if len(postData["title"] ) < 1:
            errors["title"] = "Title is required"
        if len(postData["desc"]) < 5:
            errors["desc"] = "Description should be at least 5 characters"
        
        return errors

class Book(models.Model):
    title = models.CharField(max_length=255)
    desc = models.TextField()
    uploaded_by = models.ForeignKey(User, related_name="books_uploaded", on_delete = models.CASCADE)
    users_who_like = models.ManyToManyField(User, related_name="liked_books")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = BookManager()

python_stack/django/django_fullstack/favorite_books_proj/books_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Book
from login_app.models import User

def index(request):
    if 'user_id' in request.session:
        context = {
            'all_books': Book.objects.all(),
            'user_id':request.session['user_id'],
            'user_first_name':request.session['user_first_name'],
            'user_last_name':request.session['user_last_name'],
            'user_liked_books': User.objects.get(id=request.session['user_id']).liked_books.all()
        }
        return render(request, 'books_app/index.html', context)
    else:
        return redirect('login:root')

def user_fav(request):
    if 'user_id' in request.session:
        context = {
            'user_id':request.session['user_id'],
            'user_first_name':request.session['user_first_name'],
            'user_last_name':request.session['user_last_name'],
            'user_liked_books': User.objects.get(id=request.session['user_id']).liked_books.all()
        }
        return render(request, 'books_app/user_fav.html', context)
    else:
        return redirect('login:root')

def create(request):
    if request.method == "POST":
        errors = Book.objects.validator(request.POST)
        if len(errors) > 0:
            for key, value in errors.items():
                messages.error(request, value, extra_tags='books')
            return redirect('books:root')
        else:
            user = User.objects.get(id=request.session['user_id'])
            book = Book.objects.create(title=request.POST['title'], desc=request.POST['desc'], uploaded_by=user )
            user.liked_books.add(book)
            return redirect('books:root')
    else:
        return redirect('books:root')

def like(request, book_id):
    if request.method == "POST":
        user = User.objects.get(id=request.session['user_id'])
        book = Book.objects.get(id=book_id)
        user.liked_books.add(book)
        if request.POST['which_form'] == 'books':
            return redirect('books:root')
        elif request.POST['which_form'] == 'book_view':
            return redirect('books:view', book_id=book_id)
    else:
        return redirect('books:root')

def remove_like(request, book_id):
    if request.method == "POST":
        user = User.objects.get(id=request.session['user_id'])
        book = Book.objects.get(id=book_id)
        user.liked_books.remove(book)
        return redirect('books:view', book_id=book_id)
    else:
        return redirect('books:root')

def view(request, book_id):
    context = {
        'book': Book.objects.get(id=book_id),
        'user_id':request.session['user_id'],
        'user_first_name':request.session['user_first_name'],
        'user_last_name':request.session['user_last_name'],
        'user_liked_books': User.objects.get(id=request.session['user_id']).liked_books.all()
    }
    return render(request, 'books_app/book_view.html', context)

def update(request, book_id):
    if request.POST:
        errors = Book.objects.validator(request.POST)
        if len(errors) > 0:
            for key, value in errors.items():
                messages.error(request, value, extra_tags='books')
            return redirect('books:view', book_id=book_id)
        else:
            book = Book.objects.get(id=book_id)
            book.title = request.POST['title']
            book.desc = request.POST['desc']
            book.save()
            return redirect('books:view', book_id=book_id)
    else:
        return redirect('books:view', book_id=book_id)

def delete(request, book_id):
    if request.method == "POST":
        book = Book.objects.get(id=book_id)
        book.delete()
        return redirect('books:root')
    else:
        return redirect('books:view', book_id=book_id)

python_stack/django/django_fullstack/favorite_books_proj/books_app/templates/books_app/book_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Favorite Books</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'books:root'%}">CodingDojo Books</a>
        <div class="my-2 my-lg-0 ml-auto">
            <span class="mr-4 text-light d-none d-md-inline">Welcome {{user_first_name}} {{user_last_name}}!</span>
            
            <a href="{% url 'books:user_fav' %}">
                <button class='btn btn-light btn-sm mr-4'>
                    My favorites
                </button>
            </a>
            
            <a href="{% url 'login:logout'%}">
                <button class='btn btn-secondary btn-sm float-right'>
                    Log Out
                </button>
            </a>
        </div>
    </nav>
    <div class="container mt-5">
        <div class="row">
            <div class="col-6">
                {% if user_id == book.uploaded_by.id%}
                    <form action="{% url 'books:update' book_id=book.id %}" method='post' class="form-group">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="title" value="{{book.title}}">
                        </div>
                        <p>Added by: {{book.uploaded_by.first_name}} {{book.uploaded_by.last_name}}</p>
                        <p>Added on: {{book.created_at|date:'F j, Y @ P'}}</p>
                        <p>Last updated on: {{book.updated_at|date:'F j, Y @ P'}}</p>
                        <p>Description: </p>
                        <div class="input-group mb-3">
                            <textarea class="form-control" name="desc" cols="30" rows="5">{{book.desc}}</textarea>
                        </div>
                        {% if messages %}
                        {% for message in messages %}
                        {% if "books" in message.tags %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        <button type="submit" class="btn btn-dark">Update</button> <button formmethod="POST" formaction="{% url 'books:delete' book_id=book.id %}" class="btn btn-danger">Delete</button>
                    </form>
                {% else %}
                    <h4>{{book.title}}</h4>
                    <p>Added by: {{book.uploaded_by.first_name}} {{book.uploaded_by.last_name}}</p>
                    <p>Added on: {{book.created_at|date:'F j, Y @ P'}}</p>
                    <p>Last updated on: {{book.updated_at|date:'F j, Y @ P'}}</p>
                    <p>Description: {{book.desc}}</p>
                {% endif %}
            </div>
            <div class="col-6">
                <h4>Users Who Like This Book:</h4>
                <ul>
                    {% for user in book.users_who_like.all %}
                    <li>{{user.first_name}} {{user.last_name}}</li>
                    {% endfor %}
                </ul>

                {% if book not in user_liked_books %}
                <form method="post" action="{% url 'books:like' book_id=book.id%}">
                    {% csrf_token %}
                    <input type="hidden" name="which_form" value="book_view">
                    <button type="submit" class="btn btn-link">Add to Favorites</button>
                </form>
                {% else %}
                <form method="post" action="{% url 'books:remove_like' book_id=book.id%}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Un-Favorite</button>
                </form>
                {% endif %}


            </div>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

python_stack/django/django_fullstack/favorite_books_proj/books_app/templates/books_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Favorite Books</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'books:root'%}">CodingDojo Books</a>
        <div class="my-2 my-lg-0 ml-auto">
            <span class="mr-4 text-light d-none d-md-inline">Welcome {{user_first_name}} {{user_last_name}}!</span>

            <a href="{% url 'books:user_fav' %}">
                <button class='btn btn-light btn-sm mr-4'>
                    My favorites
                </button>
            </a>

            <a href="{% url 'login:logout'%}">
                <button class='btn btn-secondary btn-sm float-right'>
                    Log Out
                </button>
            </a>
        </div>
    </nav>
    <div class="container mt-5">
        <div class="row">
            <div class="col-6">
                <h2>Add a Favorites Book</h2>
                <form action="{% url 'books:create' %}" method='post' class="form-group">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Title</span>
                        </div>
                        <input type="text" class="form-control" name="title" autofocus>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Description</span>
                        </div>
                        <textarea class="form-control" name="desc" cols="30" rows="5"></textarea>
                    </div>
                    {% if messages %}
                    {% for message in messages %}
                    {% if "books" in message.tags %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                    <button type="submit" class="btn btn-dark btn-block">Add</button>
                </form>
            </div>
            <div class="col-6">
                <h2>All Books</h2>
                {% for book in all_books reversed %}
                <div class="card mb-2">
                    <div class="card-body">
                        <a class="card-title" href="{% url 'books:view' book_id=book.id %}">
                            <p>{{book.title}}</p>
                        </a>
                        <h6 class="card-subtitle mb-2 text-muted">(added by {{book.uploaded_by.first_name}}
                            {{book.uploaded_by.last_name}})</h6>
                        {% if book in user_liked_books %}
                        <em>this is one of your favorites</em>
                        {% else %}
                        <form method="post" action="{% url 'books:like' book_id=book.id%}">
                            {% csrf_token %}
                            <input type="hidden" name="which_form" value="books">
                            <button type="submit" class="card-link btn btn-link">Add to Favorites</button>
                        </form>

                        {% endif %}
                    </div>
                </div>



                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

python_stack/django/django_fullstack/favorite_books_proj/books_app/templates/books_app/user_fav.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Favorite Books</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'books:root' %}">CodingDojo Books</a>
        <div class="my-2 my-lg-0 ml-auto">
            <span class="mr-4 text-light d-none d-md-inline">Welcome {{user_first_name}} {{user_last_name}}!</span>

            <a href="{% url 'books:user_fav' %}">
                <button class='btn btn-light btn-sm mr-4'>
                    My favorites
                </button>
            </a>

            <a href="{% url 'login:logout' %}">
                <button class='btn btn-secondary btn-sm float-right'>
                    Log Out
                </button>
            </a>
        </div>
    </nav>
    <div class="container mt-5">
        <h2>All My Favorite Books</h2>
        <ul class="list-group"></ul>
            {% for book in user_liked_books %}
                <li class="list-group-item mb-2">{{book.title}}</li> 
            {% endfor %}
        </ul>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>