python_stack/django/django_fullstack/favorite_books_proj/books_app/urls.py
from django.urls import path
from . import views
app_name = 'books'
urlpatterns = [
    path('books', views.index, name='root'),
    path('books/create', views.create, name='create'),
    path('books/<int:book_id>/like', views.like, name='like'),
    path('books/<int:book_id>/remove_like', views.remove_like, name='remove_like'),
    path('books/<int:book_id>', views.view, name='view'),
    path('books/<int:book_id>/update', views.update, name='update'),
    path('books/<int:book_id>/delete', views.delete, name='delete'),
    path('books/my_favorites', views.user_fav, name='user_fav'),
]

python_stack/django/django_fullstack/favorite_books_proj/favorite_books_proj/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('login_app.urls'), name='login'),
    path('', include('books_app.urls'), name='books'),
]

python_stack/django/django_fullstack/favorite_books_proj/login_app/urls.py
from django.urls import path
from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='root'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('success', views.success, name='success'),
    path('logout', views.logout, name='logout')
]

python_stack/django/django_fullstack/favorite_books_proj/login_app/models.py
from django.db import models
import re	# the regex module

class UserManager(models.Manager):
    def register_validator(self, postData):
        errors = {}
        EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$")
        if len(postData["first_name"]) < 2:
            errors["first_name"] = "First name should be at least 2 characters"
        elif not postData["first_name"].isalpha():
            errors["first_name"] = "First name should be letters only"
        if len(postData["last_name"]) < 2:
            errors["last_name"] = "Last name should be at least 2 characters"
        elif not postData["last_name"].isalpha():
            errors["last_name"] = "Last name should be letters only"
        if len(postData["password"]) < 8:
            errors["password"] = "Password should be at least 8 characters"
        if postData["password"] != postData["confirm_pw"]:
            errors["confirm_pw"] = "Password and confirm password does not match"
        if self.filter(email=postData["email"]):
            errors["email"] = "Email is already registered"
        if not EMAIL_REGEX.match(postData["email"]):
            errors["email"] = "Invalid email"
        return errors

    def login_validator(self, postData):
        errors = {}
        EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$")
        if len(postData["password"]) < 8:
            errors["password"] = "Password should be at least 8 characters"
        if not EMAIL_REGEX.match(postData["email"]):
            errors["email"] = "Invalid email"
        return errors

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # hidden liked_books
    # hidden books_uploaded
    objects = UserManager()

python_stack/django/django_fullstack/favorite_books_proj/login_app/views.py
from django.shortcuts import render,redirect
import bcrypt
from django.contrib import messages
from .models import User
def index(request):
    if 'user_id' in request.session:
        return redirect('books:root')
    else:
        return render(request, 'login_app/index.html')

def register(request):
    if request.method == "POST":
        errors = User.objects.register_validator(request.POST)
        if len(errors) > 0:
            for key, value in errors.items():
                messages.error(request, value, extra_tags='register')
            return redirect('login:root')
        else:
            password = request.POST['password']
            pw_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()  # create the hash    
            logged_user = User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], password=pw_hash)
            request.session['user_first_name'] = logged_user.first_name
            request.session['user_last_name'] = logged_user.last_name
            request.session['user_id'] = logged_user.id
            return redirect('login:success')
    else:
        return redirect('login:root')

def login(request):
    if request.method == "POST":
        errors = User.objects.login_validator(request.POST)
        if len(errors) > 0:
            for key, value in errors.items():
                messages.error(request, value, extra_tags='login')
            return redirect('login:root')
        user = User.objects.filter(email=request.POST['email'])
        if user:
            logged_user = user[0] 
            if bcrypt.checkpw(request.POST['password'].encode(), logged_user.password.encode()):
                request.session['user_first_name'] = logged_user.first_name
                request.session['user_last_name'] = logged_user.last_name
                request.session['user_id'] = logged_user.id
                return redirect('login:success')
            else:
                messages.error(request, "Email or Password not correct", extra_tags='login')
                return redirect('login:root')
        else:
            messages.error(request, "Email or Password not correct", extra_tags='login')
            return redirect('login:root')
    else:
        return redirect('login:root')

def success(request):
    if 'user_id' in request.session:
        messages.success(request, "Successfully registered (or logged in)!", extra_tags='logged')
        return redirect('books:root')
    else:
        return redirect('login:root')

def logout(request):
    request.session.flush()
    return redirect('login:root')

python_stack/django/django_fullstack/favorite_books_proj/login_app/templates/login_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Login & Registration</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class=" mt-5 col-6">
                <h2 class="text-center">Registration</h2>
                <form action="{% url 'login:register' %}" method='post' class="form-group">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">First Name</span>
                        </div>
                        <input type="text" class="form-control" name="first_name" autofocus >
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Last Name</span>
                        </div>
                        <input type="text" class="form-control" name="last_name" autofocus >
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Email</span>
                        </div>
                        <input type="text" class="form-control" name="email" >
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Password</span>
                        </div>
                        <input type="password" class="form-control" name="password" >
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Confirm PW</span>
                        </div>
                        <input type="password" class="form-control" name="confirm_pw" >
                    </div>
                    {% if messages %}                        
                        {% for message in messages %}
                            {% if "register" in message.tags %}
                                <div class="alert alert-danger" role="alert">
                                    {{ message }}
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <button type="submit" class="btn btn-dark btn-block">Register</button>
                </form>
            </div>
            <div class=" mt-5 col-6">
                <h2 class="text-center">Login</h2>
                <form action="{% url 'login:login' %}" method='post' class="form-group">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Email</span>
                        </div>
                        <input type="text" class="form-control" name="email" autofocus >
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Password</span>
                        </div>
                        <input type="password" class="form-control" name="password" >
                    </div>
                    {% if messages %}                        
                        {% for message in messages %}
                            {% if "login" in message.tags %}
                                <div class="alert alert-danger" role="alert">
                                    {{ message }}
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <button type="submit" class="btn btn-dark btn-block">Log In</button>
                </form>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</body>

</html>